# Megha's docker compose file
services:

  mango.services.authapi:
    image: ${DOCKER_REGISTRY-}mangoservicesauthapi
    container_name: mango.services.authapi
    build:
      context: ./Backend/Mango.Services.AuthAPI
      dockerfile: Dockerfile
      secrets:
        - source: nugetconfig
          target: nuget_config
    ports:
      - "5005:8080"
      - "7002:8081"
    networks:
      - mango-network

  mango.services.couponapi:
    image: ${DOCKER_REGISTRY-}mangoservicescouponapi
    container_name: mango.services.couponapi
    build:
      context: ./Backend/Mango.Services.CouponAPI
      dockerfile: Dockerfile
    ports:
      - "5104:8080"
      - "7001:8081"
    networks:
      - mango-network

  mango.services.emailapi:
    image: ${DOCKER_REGISTRY-}mangoservicesemailapi
    container_name: mango.services.emailapi
    build:
      context: ./Backend/Mango.Services.EmailAPI
      dockerfile: Dockerfile
      secrets:
        - source: nugetconfig
          target: nuget_config
    ports:
      - "5216:8080"
      - "7154:8081"
    networks:
      - mango-network

  mango.services.orderapi:
    image: ${DOCKER_REGISTRY-}mangoservicesorderapi
    container_name: mango.services.orderapi
    build:
      context: ./Backend/Mango.Services.OrderAPI
      dockerfile: Dockerfile
      secrets:
        - source: nugetconfig
          target: nuget_config
    ports:
      - "5201:8080"
      - "7004:8081"
    networks:
      - mango-network

  mango.services.productapi:
    image: ${DOCKER_REGISTRY-}mangoservicesproductapi
    container_name: mango.services.productapi
    build:
      context: ./Backend/Mango.Services.ProductAPI
      dockerfile: Dockerfile
    ports:
      - "5156:8080"
      - "7000:8081"
    networks:
      - mango-network

  mango.services.rewardapi:
    image: ${DOCKER_REGISTRY-}mangoservicesrewardapi
    container_name: mango.services.rewardapi
    build:
      context: ./Backend/Mango.Services.RewardAPI
      dockerfile: Dockerfile
    ports:
      - "5202:8080"
      - "7009:8081"
    networks:
      - mango-network

  mango.services.shoppingcartapi:
    image: ${DOCKER_REGISTRY-}mangoservicesshoppingcartapi
    container_name: mango.services.shoppingcartapi
    build:
      context: ./Backend/Mango.Services.ShoppingCartAPI
      dockerfile: Dockerfile
      secrets:
        - source: nugetconfig
          target: nuget_config
    ports:
      - "5220:8080"
      - "7003:8081"
    networks:
      - mango-network

  mango.web:
    image: ${DOCKER_REGISTRY-}mangoweb
    container_name: mango.web
    build:
      context: ./Frontend/Mango.Web
      dockerfile: Dockerfile
    ports:
      - "5048:8080"
      - "7136:8081"
    networks:
      - mango-network

networks:
  mango-network:
    driver: bridge

secrets:
  nugetconfig:
    file: ./nuget.config